package vistas;

import accesoADatos.AlumnoData;
import entidades.Alumno;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

public class ManejoDeDatos extends javax.swing.JInternalFrame {

    AlumnoData aData = new AlumnoData();
    Alumno al = new Alumno();

    private DefaultTableModel modelo = new DefaultTableModel() {

        public boolean isCellEditable(int f, int c) {
            return false;
        }
    };

    private TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(modelo);

    public ManejoDeDatos() {
        initComponents();
        jTabla.setShowGrid(true);//Metodo para que se ven las lines de la tabla
        jTabla.setGridColor(Color.lightGray);//Metodo para cambiar de color las lineas internas
        // Asocia el TableRowSorter al JTable
        jTabla.setRowSorter(sorter);
        bloquear();
        llenarCombo1();
        armarCabecera();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel(){
            ImageIcon icon = new ImageIcon(getClass().getResource("/Iconos/resumen-degradado-negro-lujo-fondo-negro-vignette-backgr.jpg"));
            Image image = icon.getImage();
            public void paintComponent(Graphics g){
                g.drawImage(image,0,0,getWidth(),getHeight(),this);
            }
        };
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabla = new javax.swing.JTable();
        jbModificar = new javax.swing.JButton();
        jbEliminar = new javax.swing.JButton();
        jCombo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtNombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtApellido = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtDni = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jdFecha = new com.toedter.calendar.JDateChooser();
        jrActivos = new javax.swing.JRadioButton();
        jrNoActivos = new javax.swing.JRadioButton();
        jtBuscar = new javax.swing.JTextField();
        jbSalir = new javax.swing.JButton();

        setTitle("Manejo de Datos");
        setMinimumSize(new java.awt.Dimension(25, 22));
        setPreferredSize(new java.awt.Dimension(980, 422));

        jPanel1.setToolTipText("");

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Manejo de datos de Alumnos.");

        jTabla.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        jTabla.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTablaFocusGained(evt);
            }
        });
        jTabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTabla);

        jbModificar.setText("Modificar Datos");
        jbModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModificarActionPerformed(evt);
            }
        });

        jbEliminar.setText("Dar de Baja");
        jbEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarActionPerformed(evt);
            }
        });

        jCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboItemStateChanged(evt);
            }
        });
        jCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Buscar Alumno:");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nombre:");

        jtNombre.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Apellido:");

        jtApellido.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("DNI:");

        jtDni.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Fecha de Nacimiento:");

        jdFecha.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N

        jrActivos.setBackground(new java.awt.Color(255, 255, 255));
        jrActivos.setForeground(new java.awt.Color(255, 255, 255));
        jrActivos.setText("Mostrar Alumnos Activos");
        jrActivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrActivosActionPerformed(evt);
            }
        });

        jrNoActivos.setBackground(new java.awt.Color(255, 255, 255));
        jrNoActivos.setForeground(new java.awt.Color(255, 255, 255));
        jrNoActivos.setText("Mostrar Alumnos No Activos");
        jrNoActivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrNoActivosActionPerformed(evt);
            }
        });

        jtBuscar.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jtBuscar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtBuscarFocusGained(evt);
            }
        });
        jtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtBuscarActionPerformed(evt);
            }
        });
        jtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtBuscarKeyReleased(evt);
            }
        });

        jbSalir.setText("Salir");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jbModificar)
                                .addGap(18, 18, 18)
                                .addComponent(jbEliminar)
                                .addGap(18, 18, 18)
                                .addComponent(jbSalir))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtDni, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jdFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jrActivos)
                        .addGap(31, 31, 31)
                        .addComponent(jrNoActivos)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jrActivos)
                    .addComponent(jrNoActivos))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jdFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbModificar)
                            .addComponent(jbEliminar)
                            .addComponent(jbSalir)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jdFechaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jdFechaPropertyChange
        // TODO add your handling code here:
        if (jdFecha.getDate() != null) {
            LocalDate nf = jdFecha.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        }
    }//GEN-LAST:event_jdFechaPropertyChange

    private void jTablaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTablaFocusGained
        // TODO add your handling code here:

    }//GEN-LAST:event_jTablaFocusGained

    private void jTablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablaMouseClicked
        // TODO add your handling code here:
        try {
            int fila = jTabla.getSelectedRow();//Declaro la varible fila
            jtNombre.setText((String) modelo.getValueAt(fila, 0));
            jtApellido.setText((String) modelo.getValueAt(fila, 1));
            jtDni.setText((String) modelo.getValueAt(fila, 2).toString());
            /*Para mostrar la fecha de la tabla, primero recupero el dato a String
            y despues hago la transformacion de String a Date que es el formato del jDChooser*/
            SimpleDateFormat formatoDelTexto = new SimpleDateFormat("yyyy-MM-dd");
            String fecha = modelo.getValueAt(fila, 3).toString().trim();
            Date dato = null;
            dato = formatoDelTexto.parse(fecha);
            jdFecha.setDate(dato);
            jtBuscar.setText("");

        } catch (ArrayIndexOutOfBoundsException ai) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un Alumno de la tabla.", "Error!", JOptionPane.ERROR_MESSAGE);
            return;

        } catch (ParseException ex) {
            Logger.getLogger(ManejoDeDatos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTablaMouseClicked

    private void jbModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModificarActionPerformed
        // TODO add your handling code here:
        if (jtNombre.getText().equals("") && jtApellido.getText().equals("")
                && jtDni.getText().equals("") && jdFecha.getDate() == null) {
            JOptionPane.showMessageDialog(
                    null,
                    "Por favor, complete todos los campos obligatorios:\n- Nombre\n- Apellido\n- DNI\n- Fecha de Nacimiento",
                    "Campos Incompletos, seleccione un Alumno de la lista",
                    JOptionPane.ERROR_MESSAGE
            );

            return;
        } else if (jtApellido.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "El campo Apellido se encuentra vacio!!.", "Error!", JOptionPane.ERROR_MESSAGE);
            return;
        } else if (jtDni.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "El campo DNI se encuentra vacio!!.", "Error!", JOptionPane.ERROR_MESSAGE);
            return;
        } else if (jtNombre.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "El campo Apellido se encuentra vacio!!.", "Error!", JOptionPane.ERROR_MESSAGE);
            return;
        } else if (jdFecha.getDate() == null) {
            JOptionPane.showMessageDialog(null, "El campo Fecha se encuentra vacio!!.", "Error!", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (!jtNombre.getText().matches("^[\\p{L} ]+$")) {
            JOptionPane.showMessageDialog(null, "Ingrese un Nombre válido! (solo letras y espacios).", "Error en el Nombre", JOptionPane.ERROR_MESSAGE);

            return;
        }
        if (!jtApellido.getText().matches("^[\\p{L} ]+$")) {
            JOptionPane.showMessageDialog(null, "Ingrese un Apellido válido! (solo letras y espacios).", "Error en el Apellido", JOptionPane.ERROR_MESSAGE);

            return;
        }
        if (!jtDni.getText().matches("[0-9]+")) {
            JOptionPane.showMessageDialog(null, "Ingrese un DNI válido! (solo números).", "Error en el DNI", JOptionPane.ERROR_MESSAGE);

            return;
        }

        // Obtengo los valores actuales del alumno.
        al = aData.buscarAlumnoPorDni((int) modelo.getValueAt(jTabla.getSelectedRow(), 2));

// Obtengo los nuevos valores ingresados por el usuario.
        String nuevoNombre = jtNombre.getText();
        String nuevoApellido = jtApellido.getText();
        int nuevoDni = Integer.parseInt(jtDni.getText());
        LocalDate nuevaFechaNacimiento = jdFecha.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();

// Comparo los valores actuales con los nuevos valores.
        if (al.getNombre().equals(nuevoNombre)
                && al.getApellido().equals(nuevoApellido)
                && al.getDni() == nuevoDni
                && al.getFechaNac().equals(nuevaFechaNacimiento)) {
            // No se realizaron cambios, muestra un mensaje de advertencia.
            JOptionPane.showMessageDialog(
                    null,
                    "No se realizaron cambios en los datos del alumno.",
                    "Sin Cambios",
                    JOptionPane.WARNING_MESSAGE
            );
        } else {
            int resp = JOptionPane.showConfirmDialog(null, "¿Desea guardar los datos ingresados?", "Atención!",
                    JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);

            if (resp == 0) {

                al.setNombre(jtNombre.getText());
                al.setApellido(jtApellido.getText());
                al.setDni(Integer.parseInt(jtDni.getText()));
                al.setFechaNac(jdFecha.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate());

                aData.modificarAlumno(al);
                // Actualiza los datos en el modelo de la tabla
                int fila = jTabla.getSelectedRow();
                if (fila != -1) {
                    modelo.setValueAt(nuevoNombre, fila, 0); // Actualiza el nombre
                    modelo.setValueAt(nuevoApellido, fila, 1); // Actualiza el apellido
                    modelo.setValueAt(nuevoDni, fila, 2); // Actualiza el DNI
                    modelo.setValueAt(nuevaFechaNacimiento, fila, 3); // Actualiza la fecha de nacimiento
                }

// Notifica a la tabla que los datos han cambiado
                modelo.fireTableDataChanged();
            }
        }
        borrar();
    }//GEN-LAST:event_jbModificarActionPerformed

    private void jbEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarActionPerformed
        // TODO add your handling code here:

        if (jtNombre.getText().equals("") && jtApellido.getText().equals("") && jtDni.getText().equals("") && jdFecha.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un Alumno de la tabla.", "Error!", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int resp = JOptionPane.showConfirmDialog(null, "¿Desea dar de baja al Alumno seleccionado?", "Atención!",
                JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        int fila = jTabla.getSelectedRow();
        if (resp == 0) {
            al = aData.buscarAlumnoPorDni((int) modelo.getValueAt(fila, 2));
            if (al.isEstado() == true) {
                aData.eliminarAlumno(al.getIdAlumno());
                modelo.fireTableDataChanged();
                borrar();
                modelo.setValueAt("Inactivo/a", fila, 4);
            } else {
                JOptionPane.showMessageDialog(null, "El Alumno seleccionado ya se encuentra dado de baja.");
            }

        }

    }//GEN-LAST:event_jbEliminarActionPerformed

    private void jComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboItemStateChanged

    private void jComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboActionPerformed
        // TODO add your handling code here:
        if (jCombo.getSelectedItem().equals("Por Dni")) {

            borrar();
            activar();
            jtBuscar.setText("Ingrese DNI");
            borrarFilas();
        } else if (jCombo.getSelectedItem().equals("Por Nombre")) {

            borrar();
            activar();
            jtBuscar.setText("Ingrese Nombre");
            borrarFilas();
        } else if (jCombo.getSelectedItem().equals("Por Apellido")) {

            borrar();
            activar();
            jtBuscar.setText("Ingrese Apellido");
            borrarFilas();
        } else if (jCombo.getSelectedItem().equals("Todos")) {

            borrar();
            activar();
            jtBuscar.setEnabled(false);
            borrarFilas();
            for (Alumno alu : aData.listarTodosAlumnos()) {
                String estado = alu.isEstado() ? "Activo/a" : "Inactivo/a";
                modelo.addRow(new Object[]{
                    alu.getNombre(), alu.getApellido(), alu.getDni(), alu.getFechaNac(), estado
                });

            }
            jTabla.repaint();

        } else if (jCombo.getSelectedIndex() == 0) {

            borrarFilas();
            borrar();
            bloquear();

        }
    }//GEN-LAST:event_jComboActionPerformed

    private void jrActivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrActivosActionPerformed
        // TODO add your handling code here

        borrarFilas();
        if (jCombo.getSelectedItem().equals("Por Nombre")) {
            jrNoActivos.setSelected(false);
            activosNombre();
            jTabla.repaint();
        } else if (jCombo.getSelectedItem().equals("Por Apellido")) {
            jrNoActivos.setSelected(false);
            activosApellido();
            jTabla.repaint();
        } else if (jCombo.getSelectedItem().equals("Por Dni")) {
            jrNoActivos.setSelected(false);
            activosDni();
            jTabla.repaint();
        } else if (jCombo.getSelectedItem().equals("Todos")) {
            jrNoActivos.setSelected(false);
            todosActivos();
            jTabla.repaint();
        }

    }//GEN-LAST:event_jrActivosActionPerformed

    private void jrNoActivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrNoActivosActionPerformed
        // TODO add your handling code here:

        borrarFilas();
        if (jCombo.getSelectedItem().equals("Por Nombre")) {
            jrActivos.setSelected(false);
            noActivosNombre();
            jTabla.repaint();
        } else if (jCombo.getSelectedItem().equals("Por Apellido")) {
            jrActivos.setSelected(false);
            noActivosApellido();
            jTabla.repaint();
        } else if (jCombo.getSelectedItem().equals("Por Dni")) {
            jrActivos.setSelected(false);
            noActivosDni();
            jTabla.repaint();
        } else if (jCombo.getSelectedItem().equals("Todos")) {

            jrActivos.setSelected(false);
            todosNoActivos();
            jTabla.repaint();
        }

    }//GEN-LAST:event_jrNoActivosActionPerformed

    private void jtBuscarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtBuscarFocusGained
        // TODO add your handling code here:
        if (jtBuscar.getText().equals("Ingrese DNI")) {
            jtBuscar.setText("");
            jrActivos.setEnabled(true);
            jrNoActivos.setEnabled(true);
        }
        if (jtBuscar.getText().equalsIgnoreCase("Ingrese Apellido")) {
            jtBuscar.setText("");
            jrActivos.setEnabled(true);
            jrNoActivos.setEnabled(true);
        }
        if (jtBuscar.getText().equalsIgnoreCase("Ingrese Nombre")) {
            jtBuscar.setText("");
            jrActivos.setEnabled(true);
            jrNoActivos.setEnabled(true);
        }
    }//GEN-LAST:event_jtBuscarFocusGained

    private void jtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtBuscarActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jtBuscarActionPerformed

    private void jtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtBuscarKeyReleased
        // TODO add your handling code here:
        if (jCombo.getSelectedItem().equals("Por Apellido")) {
            borrarFilas();

            for (Alumno alu : aData.listarTodosAlumnos()) {
                if (alu.getApellido().toLowerCase().startsWith(jtBuscar.getText().toLowerCase())) {
                    String estado = alu.isEstado() ? "Activo/a" : "Inactivo/a";
                    modelo.addRow(new Object[]{
                        alu.getNombre(), alu.getApellido(), alu.getDni(), alu.getFechaNac(), estado
                    });
                }
            }

            if (jtBuscar.getText().equals("")) {
                borrarFilas();
            }
        }

        if (jCombo.getSelectedItem().equals("Por Dni")) {
            borrarFilas();
            for (Alumno alu : aData.listarTodosAlumnos()) {
                if (String.valueOf(alu.getDni()).startsWith(jtBuscar.getText())) {
                    String estado = alu.isEstado() ? "Activo/a" : "Inactivo/a";
                    modelo.addRow(new Object[]{
                        alu.getNombre(), alu.getApellido(), alu.getDni(), alu.getFechaNac(), estado
                    });
                }
            }
            if (jtBuscar.getText().equals("")) {
                borrarFilas();
            }
        }
        if (jCombo.getSelectedItem().equals("Por Nombre")) {
            borrarFilas();
            for (Alumno alu : aData.listarTodosAlumnos()) {
                if (alu.getNombre().toLowerCase().startsWith(jtBuscar.getText().toLowerCase())) {
                    String estado = alu.isEstado() ? "Activo/a" : "Inactivo/a";
                    modelo.addRow(new Object[]{
                        alu.getNombre(), alu.getApellido(), alu.getDni(), alu.getFechaNac(), estado
                    });
                }
            }
            if (jtBuscar.getText().equals("")) {
                borrarFilas();
            }
        }

    }//GEN-LAST:event_jtBuscarKeyReleased

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jbSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jCombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTabla;
    private javax.swing.JButton jbEliminar;
    private javax.swing.JButton jbModificar;
    private javax.swing.JButton jbSalir;
    private com.toedter.calendar.JDateChooser jdFecha;
    private javax.swing.JRadioButton jrActivos;
    private javax.swing.JRadioButton jrNoActivos;
    private javax.swing.JTextField jtApellido;
    private javax.swing.JTextField jtBuscar;
    private javax.swing.JTextField jtDni;
    private javax.swing.JTextField jtNombre;
    // End of variables declaration//GEN-END:variables

    private void llenarCombo1() {
        jCombo.addItem("");
        jCombo.addItem("Por Dni");
        jCombo.addItem("Por Nombre");
        jCombo.addItem("Por Apellido");
        jCombo.addItem("Todos");
    }

    private void borrar() {
        jtDni.setText("");
        jrActivos.setSelected(false);
        jrNoActivos.setSelected(false);
        jtApellido.setText("");
        jtNombre.setText("");
        jtBuscar.setText("");
        jdFecha.setDate(null);
    }

    private void armarCabecera() {
        modelo.addColumn("Nombre");
        modelo.addColumn("Apellido");
        modelo.addColumn("DNI");
        modelo.addColumn("Fecha de Nacimiento");
        modelo.addColumn("Estado");
        jTabla.setModel(modelo);
    }

    private void borrarFilas() {
        int f = modelo.getRowCount();
        for (int i = f - 1; i >= 0; i--) {
            modelo.removeRow(i);
        }
    }

    private void bloquear() {
        jrActivos.setEnabled(false);
        jrNoActivos.setEnabled(false);
        jtNombre.setEnabled(false);
        jtApellido.setEnabled(false);
        jtDni.setEnabled(false);
        jdFecha.setEnabled(false);
        jTabla.setEnabled(false);
        jtBuscar.setEnabled(false);
////        jbBorrar.setEnabled(false);
        jbModificar.setEnabled(false);
        jbEliminar.setEnabled(false);
    }

    private void activar() {
        jrActivos.setEnabled(true);
        jrNoActivos.setEnabled(true);
        jtNombre.setEnabled(true);
        jtApellido.setEnabled(true);
        jtDni.setEnabled(true);
        jdFecha.setEnabled(true);
        jTabla.setEnabled(true);
        jtBuscar.setEnabled(true);
//        jbBorrar.setEnabled(true);
        jbModificar.setEnabled(true);
        jbEliminar.setEnabled(true);
    }

    private void activosNombre() {
        char letra;
        if (jrActivos.isSelected()) {
            if (!jtBuscar.getText().equals("")) {
                letra = jtBuscar.getText().toUpperCase().charAt(0); // Obtener la primera letra ingresada
                // Llamar al método en AlumnoData para obtener alumnos activos que comienzan con la letra ingresada
                List<Alumno> alumnos = aData.obtenerActivosPorNombre(letra);
                System.out.println(alumnos);
                // Actualizar la tabla con los resultados obtenidos
                for (Alumno alu : alumnos) {
                    String estado = alu.isEstado() ? "Activo/a" : "Inactivo/a";
                    modelo.addRow(new Object[]{
                        alu.getNombre(), alu.getApellido(), alu.getDni(), alu.getFechaNac(), estado
                    });
                }
            }
        } else {
            if (!jtBuscar.getText().equals("")) {
                letra = jtBuscar.getText().toUpperCase().charAt(0); // Obtener la primera letra ingresada
                // Llamar al método en AlumnoData para obtener alumnos activos que comienzan con la letra ingresada
                // Mostrar todos los alumnos cuando el botón esté deseleccionado
                for (Alumno alu : aData.listarTodosPorNombre(letra)) {
                    String estado = alu.isEstado() ? "Activo/a" : "Inactivo/a";
                    modelo.addRow(new Object[]{
                        alu.getNombre(), alu.getApellido(), alu.getDni(), alu.getFechaNac(), estado
                    });
                }
            }

        }
    }

    private void noActivosNombre() {
        char letra;
        if (jrNoActivos.isSelected()) {
            if (!jtBuscar.getText().equals("")) {
                letra = jtBuscar.getText().toUpperCase().charAt(0); // Obtener la primera letra ingresada
                // Llamar al método en AlumnoData para obtener alumnos activos que comienzan con la letra ingresada
                List<Alumno> alumnos = aData.obtenerNoActivosPorNombre(letra);
                System.out.println(alumnos);
                // Actualizar la tabla con los resultados obtenidos
                for (Alumno alu : alumnos) {
                    String estado = alu.isEstado() ? "Activo/a" : "Inactivo/a";
                    modelo.addRow(new Object[]{
                        alu.getNombre(), alu.getApellido(), alu.getDni(), alu.getFechaNac(), estado
                    });
                }
            }
        } else {
            if (!jtBuscar.getText().equals("")) {
                letra = jtBuscar.getText().toUpperCase().charAt(0); // Obtener la primera letra ingresada
                // Llamar al método en AlumnoData para obtener alumnos activos que comienzan con la letra ingresada
                // Mostrar todos los alumnos cuando el botón esté deseleccionado
                for (Alumno alu : aData.listarTodosPorNombre(letra)) {
                    String estado = alu.isEstado() ? "Activo/a" : "Inactivo/a";
                    modelo.addRow(new Object[]{
                        alu.getNombre(), alu.getApellido(), alu.getDni(), alu.getFechaNac(), estado
                    });
                }
            }

        }
    }

    private void activosApellido() {
        char letra;
        if (jrActivos.isSelected()) {
            if (!jtBuscar.getText().equals("")) {
                letra = jtBuscar.getText().toUpperCase().charAt(0); // Obtener la primera letra ingresada
                // Llamar al método en AlumnoData para obtener alumnos activos que comienzan con la letra ingresada
                List<Alumno> alumnos = aData.obtenerActivosPorApellido(letra);
                System.out.println(alumnos);
                // Actualizar la tabla con los resultados obtenidos
                for (Alumno alu : alumnos) {
                    String estado = alu.isEstado() ? "Activo/a" : "Inactivo/a";
                    modelo.addRow(new Object[]{
                        alu.getNombre(), alu.getApellido(), alu.getDni(), alu.getFechaNac(), estado
                    });
                }
            }
        } else {
            if (!jtBuscar.getText().equals("")) {
                letra = jtBuscar.getText().toUpperCase().charAt(0); // Obtener la primera letra ingresada
                // Llamar al método en AlumnoData para obtener alumnos activos que comienzan con la letra ingresada
                // Mostrar todos los alumnos cuando el botón esté deseleccionado
                for (Alumno alu : aData.listarTodosPorApellido(letra)) {
                    String estado = alu.isEstado() ? "Activo/a" : "Inactivo/a";
                    modelo.addRow(new Object[]{
                        alu.getNombre(), alu.getApellido(), alu.getDni(), alu.getFechaNac(), estado
                    });
                }
            }

        }
    }

    private void noActivosApellido() {
        char letra;
        if (jrNoActivos.isSelected()) {
            if (!jtBuscar.getText().equals("")) {
                letra = jtBuscar.getText().toUpperCase().charAt(0); // Obtener la primera letra ingresada
                // Llamar al método en AlumnoData para obtener alumnos activos que comienzan con la letra ingresada
                List<Alumno> alumnos = aData.obtenerNoActivosPorApellido(letra);
                System.out.println(alumnos);
                // Actualizar la tabla con los resultados obtenidos
                for (Alumno alu : alumnos) {
                    String estado = alu.isEstado() ? "Activo/a" : "Inactivo/a";
                    modelo.addRow(new Object[]{
                        alu.getNombre(), alu.getApellido(), alu.getDni(), alu.getFechaNac(), estado
                    });
                }
            }
        } else {
            if (!jtBuscar.getText().equals("")) {
                letra = jtBuscar.getText().toUpperCase().charAt(0); // Obtener la primera letra ingresada
                // Llamar al método en AlumnoData para obtener alumnos activos que comienzan con la letra ingresada
                // Mostrar todos los alumnos cuando el botón esté deseleccionado
                for (Alumno alu : aData.listarTodosPorApellido(letra)) {
                    String estado = alu.isEstado() ? "Activo/a" : "Inactivo/a";
                    modelo.addRow(new Object[]{
                        alu.getNombre(), alu.getApellido(), alu.getDni(), alu.getFechaNac(), estado
                    });
                }
            }

        }
    }

    private void activosDni() {
        char letra;
        if (jrActivos.isSelected()) {
            if (!jtBuscar.getText().equals("")) {
                letra = jtBuscar.getText().toUpperCase().charAt(0); // Obtener la primera letra ingresada
                // Llamar al método en AlumnoData para obtener alumnos activos que comienzan con la letra ingresada
                List<Alumno> alumnos = aData.obtenerActivosPorDni(letra);
                System.out.println(alumnos);
                // Actualizar la tabla con los resultados obtenidos
                for (Alumno alu : alumnos) {
                    String estado = alu.isEstado() ? "Activo/a" : "Inactivo/a";
                    modelo.addRow(new Object[]{
                        alu.getNombre(), alu.getApellido(), alu.getDni(), alu.getFechaNac(), estado
                    });
                }
            }
        } else {
            if (!jtBuscar.getText().equals("")) {
                letra = jtBuscar.getText().toUpperCase().charAt(0); // Obtener la primera letra ingresada
                // Llamar al método en AlumnoData para obtener alumnos activos que comienzan con la letra ingresada
                // Mostrar todos los alumnos cuando el botón esté deseleccionado
                for (Alumno alu : aData.listarTodosPorDni(letra)) {
                    String estado = alu.isEstado() ? "Activo/a" : "Inactivo/a";
                    modelo.addRow(new Object[]{
                        alu.getNombre(), alu.getApellido(), alu.getDni(), alu.getFechaNac(), estado
                    });
                }
            }

        }
    }

    private void noActivosDni() {
        char letra;
        if (jrNoActivos.isSelected()) {
            if (!jtBuscar.getText().equals("")) {
                letra = jtBuscar.getText().toUpperCase().charAt(0); // Obtener la primera letra ingresada
                // Llamar al método en AlumnoData para obtener alumnos activos que comienzan con la letra ingresada
                List<Alumno> alumnos = aData.obtenerNoActivosPorDni(letra);
                System.out.println(alumnos);
                // Actualizar la tabla con los resultados obtenidos
                for (Alumno alu : alumnos) {
                    String estado = alu.isEstado() ? "Activo/a" : "Inactivo/a";
                    modelo.addRow(new Object[]{
                        alu.getNombre(), alu.getApellido(), alu.getDni(), alu.getFechaNac(), estado
                    });
                }
            }
        } else {
            if (!jtBuscar.getText().equals("")) {
                letra = jtBuscar.getText().toUpperCase().charAt(0); // Obtener la primera letra ingresada
                // Llamar al método en AlumnoData para obtener alumnos activos que comienzan con la letra ingresada
                // Mostrar todos los alumnos cuando el botón esté deseleccionado
                for (Alumno alu : aData.listarTodosPorDni(letra)) {
                    String estado = alu.isEstado() ? "Activo/a" : "Inactivo/a";
                    modelo.addRow(new Object[]{
                        alu.getNombre(), alu.getApellido(), alu.getDni(), alu.getFechaNac(), estado
                    });
                }
            }

        }
    }

    private void todosActivos() {
        char letra;
        if (jrActivos.isSelected()) {
            if (jCombo.getSelectedItem().equals("Todos")) {

                List<Alumno> alumnos = aData.listarTodosActivos();

                // Actualizar la tabla con los resultados obtenidos
                for (Alumno alu : alumnos) {
                    String estado = alu.isEstado() ? "Activo/a" : "Inactivo/a";
                    modelo.addRow(new Object[]{
                        alu.getNombre(), alu.getApellido(), alu.getDni(), alu.getFechaNac(), estado
                    });
                }
            }
        } else {

            for (Alumno alu : aData.listarTodosAlumnos()) {
                String estado = alu.isEstado() ? "Activo/a" : "Inactivo/a";
                modelo.addRow(new Object[]{
                    alu.getNombre(), alu.getApellido(), alu.getDni(), alu.getFechaNac(), estado
                });
            }
        }
    }

    private void todosNoActivos() {
        if (jrNoActivos.isSelected()) {
            if (jCombo.getSelectedItem().equals("Todos")) {

                List<Alumno> alumnos = aData.listarTodosNoActivos();

                // Actualizar la tabla con los resultados obtenidos
                for (Alumno alu : alumnos) {
                    String estado = alu.isEstado() ? "Activo/a" : "Inactivo/a";
                    modelo.addRow(new Object[]{
                        alu.getNombre(), alu.getApellido(), alu.getDni(), alu.getFechaNac(), estado
                    });
                }
            }
        } else {

            for (Alumno alu : aData.listarTodosAlumnos()) {
                String estado = alu.isEstado() ? "Activo/a" : "Inactivo/a";
                modelo.addRow(new Object[]{
                    alu.getNombre(), alu.getApellido(), alu.getDni(), alu.getFechaNac(), estado
                });
            }
        }
    }
}
