/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import accesoADatos.MateriaData;
import entidades.Materia;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Miki
 */
public class mtodo extends javax.swing.JInternalFrame {

    MateriaData mData = new MateriaData();
    Materia mat = new Materia();

    public mtodo() {
        initComponents();
        jBmodifi.setEnabled(false);
        jBeliminar.setEnabled(false);
        jRinac.setEnabled(false);
        jRactivo.setEnabled(false);
        jTaño1.setEnabled(false);
        jTnombre1.setEnabled(false);
        jTid.setEnabled(false);
        // jTid.setEnabled(false);
        jTid.setEditable(false);

    }

    public void mostrar() {
        DefaultTableModel tablita = new DefaultTableModel();
        tablita.addColumn("Id");
        tablita.addColumn("Nombre");
        tablita.addColumn("Año");
        tablita.addColumn("Estado");
        jTvisor.setModel(tablita);
        //mData.listarMaterias();
        for (Materia mat : mData.listarMaterias()) {
            tablita.addRow(new Object[]{
                mat.getIdMateria(), mat.getNombre(), mat.getAñoMateria(), mat.isActivo()
            });

        }

    }

    public void mostrarf() {
        DefaultTableModel tablita = new DefaultTableModel();
        tablita.addColumn("Id");
        tablita.addColumn("Nombre");
        tablita.addColumn("Año");
        tablita.addColumn("Estado");
        jTvisor.setModel(tablita);
        //mData.listarMaterias();
        for (Materia mat : mData.listarMateriasf()) {
            tablita.addRow(new Object[]{
                mat.getIdMateria(), mat.getNombre(), mat.getAñoMateria(), mat.isActivo()
            });

        }

    }

    public void mostrart() {
        DefaultTableModel tablita = new DefaultTableModel();
        tablita.addColumn("Id");
        tablita.addColumn("Nombre");
        tablita.addColumn("Año");
        tablita.addColumn("Estado");
        jTvisor.setModel(tablita);
        //mData.listarMaterias();
        for (Materia mat : mData.listarMateriast()) {

            tablita.addRow(new Object[]{
                mat.getIdMateria(), mat.getNombre(), mat.getAñoMateria(), mat.isActivo()});

        }

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTvisor = new javax.swing.JTable();
        jBactivas = new javax.swing.JButton();
        jBinac = new javax.swing.JButton();
        jBtodas = new javax.swing.JButton();
        jBsalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLnombre = new javax.swing.JLabel();
        jLaño = new javax.swing.JLabel();
        jTnombre = new javax.swing.JTextField();
        jTaño = new javax.swing.JTextField();
        jBguardar1 = new javax.swing.JButton();
        jBeliminar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLmodifi = new javax.swing.JLabel();
        jLnombre1 = new javax.swing.JLabel();
        jLaño1 = new javax.swing.JLabel();
        jTnombre1 = new javax.swing.JTextField();
        jTaño1 = new javax.swing.JTextField();
        jBsele = new javax.swing.JButton();
        jBmodifi = new javax.swing.JButton();
        jLid = new javax.swing.JLabel();
        jTid = new javax.swing.JTextField();
        jLestado = new javax.swing.JLabel();
        jRactivo = new javax.swing.JRadioButton();
        jRinac = new javax.swing.JRadioButton();

        setMinimumSize(new java.awt.Dimension(0, 0));
        setPreferredSize(new java.awt.Dimension(1045, 500));

        jTvisor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTvisor);

        jBactivas.setText("Activas");
        jBactivas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBactivasActionPerformed(evt);
            }
        });

        jBinac.setText("Inactivas");
        jBinac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBinacActionPerformed(evt);
            }
        });

        jBtodas.setText("Todas");
        jBtodas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtodasActionPerformed(evt);
            }
        });

        jBsalir.setText("Salir");
        jBsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsalirActionPerformed(evt);
            }
        });

        jLabel1.setText("Nueva Materia");

        jLnombre.setText("Nombre");

        jLaño.setText("Año");

        jTnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTnombreActionPerformed(evt);
            }
        });

        jBguardar1.setText("Guardar");
        jBguardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBguardar1ActionPerformed(evt);
            }
        });

        jBeliminar.setText("Eliminar");
        jBeliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBeliminarActionPerformed(evt);
            }
        });

        jLabel2.setText("Materias:");

        jLmodifi.setText("Modificar Materia");

        jLnombre1.setText("Nombre");

        jLaño1.setText("Año");

        jTaño1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTaño1ActionPerformed(evt);
            }
        });

        jBsele.setText("Seleccionar");
        jBsele.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBseleActionPerformed(evt);
            }
        });

        jBmodifi.setText("Modificar");
        jBmodifi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBmodifiActionPerformed(evt);
            }
        });

        jLid.setText("Id");

        jLestado.setText("Estado");

        jRactivo.setText("Activo");
        jRactivo.setToolTipText("");

        jRinac.setText("inactivo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1031, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLnombre)
                                            .addComponent(jLaño))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTnombre)
                                            .addComponent(jTaño, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(52, 52, 52)
                                .addComponent(jLmodifi))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBguardar1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(134, 134, 134)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLnombre1)
                                            .addComponent(jLaño1)
                                            .addComponent(jLid)
                                            .addComponent(jLestado))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jTnombre1, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                                                .addComponent(jTaño1)
                                                .addComponent(jTid))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jRactivo)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jRinac))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(126, 126, 126)
                                        .addComponent(jBsele)
                                        .addGap(1, 1, 1)
                                        .addComponent(jBmodifi)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jBeliminar)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 170, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jBactivas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBinac)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBtodas)
                                .addGap(82, 82, 82))
                            .addComponent(jBsalir, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBactivas)
                            .addComponent(jBinac)
                            .addComponent(jBtodas)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBsalir)
                        .addGap(12, 12, 12))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLmodifi))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLnombre)
                            .addComponent(jTnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLnombre1)
                                .addComponent(jTnombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLaño)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTaño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLaño1)
                                .addComponent(jTaño1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLid)
                            .addComponent(jTid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLestado)
                            .addComponent(jRactivo)
                            .addComponent(jRinac))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBsele)
                            .addComponent(jBmodifi)
                            .addComponent(jBeliminar)
                            .addComponent(jBguardar1))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBactivasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBactivasActionPerformed
        // TODO add your handling code here:
        mostrar();
        jTnombre1.setText("");
        jTaño1.setText("");
        jTid.setText("");
        jRactivo.setSelected(false);
        jRinac.setSelected(false);
        jTaño1.setEnabled(false);
        jTnombre1.setEnabled(false);
        jTid.setEnabled(false);

    }//GEN-LAST:event_jBactivasActionPerformed

    private void jBtodasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtodasActionPerformed
        // TODO add your handling code here:

        mostrart();
        jTnombre1.setText("");
        jTaño1.setText("");
        jTid.setText("");
        jRactivo.setSelected(false);
        jRinac.setSelected(false);
        jTaño1.setEnabled(false);
        jTnombre1.setEnabled(false);
        jTid.setEnabled(false);


    }//GEN-LAST:event_jBtodasActionPerformed

    private void jBinacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBinacActionPerformed

        mostrarf();
        jTnombre1.setText("");
        jTaño1.setText("");
        jTid.setText("");// TODO add your handling code here:
        jRactivo.setSelected(false);
        jRinac.setSelected(false);
        jTaño1.setEnabled(false);
        jTnombre1.setEnabled(false);
        jTid.setEnabled(false);
    }//GEN-LAST:event_jBinacActionPerformed

    private void jBsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsalirActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jBsalirActionPerformed

    private void jBguardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBguardar1ActionPerformed
        // TODO add your handling code here:
        try {
            if ((jTnombre.getText().equals("")) || (jTaño.getText().equals(""))) { //si el campo nombre o año estan vacios entra al if
                JOptionPane.showMessageDialog(this, "Hay campos vacios");//muestra el msj
            } else {
                mat.setNombre(jTnombre.getText());//asigna el nombre a la materia
                mat.setAñoMateria(Integer.parseInt(jTaño.getText()));//asigna el año a la materia
                mat.setActivo(true);//le asigna el valor true para que este activa
                mData.guardarMateria(mat);//ejecuta guardar materia
                jTaño.setText("");//deja el campo vacio
                jTnombre.setText("");//deja el campo vacio   
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ingrese datos correctos");//si por ej escribe string en vez d int en año muestra el msj
        }

    }//GEN-LAST:event_jBguardar1ActionPerformed

    private void jTnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTnombreActionPerformed

    private void jTaño1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTaño1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTaño1ActionPerformed

    private void jBseleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBseleActionPerformed
        // TODO add your handling code here:
        int exito;
        try {
            int fila = jTvisor.getSelectedRow();//Declaro la varible fila
            jTnombre1.setText((String) jTvisor.getValueAt(fila, 1));
            jTaño1.setText((String) jTvisor.getValueAt(fila, 2).toString());
            jTid.setText((String) jTvisor.getValueAt(fila, 0).toString());
            if (jTvisor.getValueAt(fila, 3).equals(true)) {
                jRactivo.setSelected(true);
                jRactivo.setEnabled(false);
                jRinac.setEnabled(false);
                exito = 1;

            } else {
                jRinac.setSelected(true);
                jRinac.setEnabled(false);
                jRactivo.setEnabled(true);
                exito = 2;

            }
            /*Para mostrar la fecha de la tabla, primero recupero el dato a String
            y despues hago la transformacion de String a Date que es el formato del jDChooser*/

        } catch (ArrayIndexOutOfBoundsException ai) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar una Materia de la tabla.", "Error!", JOptionPane.ERROR_MESSAGE);
            return;

        }
        jBmodifi.setEnabled(true);
        if (exito == 1) {
            jBeliminar.setEnabled(true);

        } else {
            jBeliminar.setEnabled(false);
        }

        jTnombre1.getText();
        jTaño1.getText();
        jTaño1.setEnabled(true);
        jTnombre1.setEnabled(true);


    }//GEN-LAST:event_jBseleActionPerformed

    private void jBmodifiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBmodifiActionPerformed
        // TODO add your handling code here:
        try {
            if ((jTnombre1.getText().equals("")) || (jTaño1.getText().equals(""))) { //si el campo nombre o año estan vacios entra al if
                JOptionPane.showMessageDialog(this, "Hay campos vacios");//muestra el msj
            } else {
                mat.setIdMateria(Integer.parseInt(jTid.getText()));
                mat.setNombre(jTnombre1.getText());
                mat.setAñoMateria(Integer.parseInt(jTaño1.getText()));
                if (jRactivo.isSelected()) {
                    mat.setActivo(true);

                }
                mData.modificarMateria(mat);

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ingrese datos correctos");//si por ej escribe string en vez d int en año muestra el msj
        }

//        jTnombre1.setText("");
//        jTaño1.setText("");
//        jTid.setText("");

    }//GEN-LAST:event_jBmodifiActionPerformed

    private void jBeliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBeliminarActionPerformed

        mData.eliminarMateria(Integer.parseInt(jTid.getText()));
        jTnombre1.setText("");
        jTaño1.setText("");
        jTid.setText("");


    }//GEN-LAST:event_jBeliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBactivas;
    private javax.swing.JButton jBeliminar;
    private javax.swing.JButton jBguardar1;
    private javax.swing.JButton jBinac;
    private javax.swing.JButton jBmodifi;
    private javax.swing.JButton jBsalir;
    private javax.swing.JButton jBsele;
    private javax.swing.JButton jBtodas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLaño;
    private javax.swing.JLabel jLaño1;
    private javax.swing.JLabel jLestado;
    private javax.swing.JLabel jLid;
    private javax.swing.JLabel jLmodifi;
    private javax.swing.JLabel jLnombre;
    private javax.swing.JLabel jLnombre1;
    private javax.swing.JRadioButton jRactivo;
    private javax.swing.JRadioButton jRinac;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTaño;
    private javax.swing.JTextField jTaño1;
    private javax.swing.JTextField jTid;
    private javax.swing.JTextField jTnombre;
    private javax.swing.JTextField jTnombre1;
    private javax.swing.JTable jTvisor;
    // End of variables declaration//GEN-END:variables
}
